"""Descripción de la modificación

Revision ID: 0dcab3679a51
Revises: 5d9ea88262b4
Create Date: 2023-12-10 22:53:05.955263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dcab3679a51'
down_revision: Union[str, None] = '5d9ea88262b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('copies_available', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'copies_available')
    # ### end Alembic commands ###
