"""Descripción de la modificación

Revision ID: 122e6ba8651a
Revises: 0fefe42198a5
Create Date: 2023-12-10 23:08:15.624400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '122e6ba8651a'
down_revision: Union[str, None] = '0fefe42198a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
