"""Descripción de la modificación

Revision ID: cd75a40f5062
Revises: 723abbb68ebc
Create Date: 2023-12-10 22:30:55.738730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd75a40f5062'
down_revision: Union[str, None] = '723abbb68ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('overdue_fine', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'overdue_fine')
    # ### end Alembic commands ###
