"""Descripción de la modificación

Revision ID: fe032932f6df
Revises: cd75a40f5062
Create Date: 2023-12-10 22:34:17.762041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe032932f6df'
down_revision: Union[str, None] = 'cd75a40f5062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('copies_available', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'copies_available')
    # ### end Alembic commands ###
